[build]
  command = "npm install"
  functions = "functions"
  publish = "public"

[build.environment]
  NODE_VERSION = "20.18.1"

[functions]
  external_node_modules = ["ejs"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = false
